### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tancheng** [tancheng/CGRA-Mapper#1]
- [x] Successor in DFG should be outport dependent.
- [x] Current 'phi' assumes single predecessor, need check true/false for connection.
- [x] Should connect 'br' with all 'store' in DFG?
- [ ] Need to check data dependency in array?
